# Generated by Django 5.2.4 on 2025-07-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaches',
            name='password',
            field=models.CharField(default='mani@1234', max_length=128),
            preserve_default=False,
        ),
    ]
