# Generated by Django 5.2.4 on 2025-08-03 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('months_paid', models.IntegerField(default=1)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(default='card', max_length=50)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='home.coaches')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='home.users')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
