# Generated by Django 5.2.4 on 2025-08-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
