# Generated by Django 5.2.4 on 2025-08-12 17:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_users_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaches',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
