# Generated by Django 5.2.4 on 2025-08-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0002_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
